### ISSUE TITLE
Adding Social Media Links in Footer

### ISSUE THREAD

**Issue by smilegupta** [smilegupta/portfolio-smilegupta#1]

**Comment by chinmaym07** [comment]
Hey @smilegupta  can I try this .?

**Comment by smilegupta** [comment]
@chinmaym07  Sure Chinmay

**Comment by chinmaym07** [comment]
Hey @smilegupta . I have opened a pr #5 for this issue. Please review.

**Comment by smilegupta** [comment]
@chinmaym07 Added a comment checkout out. I am open for discussions
